### ISSUE TITLE
Unable to create new draft doi's via file upload

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#256]
Ruby error being returned from validate call for new XML file uploads in test:

#<ActiveRecord::RecordNotFound: ActiveRecord::RecordNotFound>

Possibly authorisation related under the hood in lupo

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_13ver)

**Comment by richardhallett** [comment]
Stack trace is:

app/controllers/dois_controller.rb, line 479
--------------------------------------------

``` ruby
  474   
  475     protected
  476   
  477     def set_doi
  478       @doi = Doi.where(doi: params[:id]).first
> 479       fail ActiveRecord::RecordNotFound unless @doi.present?
  480     end
  481   
  482     def set_include
  483       if params[:include].present?
  484         @include = params[:include].split(",").map { |i| i.downcase.underscore.to_sym }
```

**Comment by richardhallett** [comment]
The problem is the client_id is not being sent through from bracco, the model appears undefined. This maybe related due to proxy nature of the models.

**Comment by yohell** [comment]
Original reporter here, should I workaround or hold off for now? Eg should I create a DOI without the metadata for now, just so the researchers can use their DOI, and then update with metadata at whatever point later once this bug is resolved? (aka do you expect quick resolution here? :-)

**Comment by richardhallett** [comment]
We're just deploying a fix now, this should hopefully get it working again. You can of course create draft DOI's to reserve, but you wouldnt be able to push them to findable without the metadata.

**Comment by yohell** [comment]
Sorry, can't get it to work. Same symptoms; nonreactive create button, red frame to metadata field. 

Tried logging out/logging in, and force refreshing the page to bypass cache, but no luck.

Maybe there's some deployment lag or caching effects? Or are there additional issues?

**Comment by yohell** [comment]
Tried again today, still no luck.

**Comment by yohell** [comment]
I don't know if it helps, but the metadata field seems to output to the firefox console once I put an url into it, if that helps:

> {…}
> ​_bodyBlob: Blob
> ​​size: 87
> ​​type: "application/json"
> ​​<prototype>: BlobPrototype { slice: slice(), stream: stream(), text: text(), … }
> ​_bodyInit: Blob
> ​​size: 87
> ​​type: "application/json"
> ​​<prototype>: BlobPrototype { slice: slice(), stream: stream(), text: text(), … }
> ​headers: Object { map: {…} }
> ​ok: false
> ​status: 404
> ​statusText: "Not Found"
> ​type: "default"
> ​url: "https://api.datacite.org/dois/validate"
> <prototype>: Object { bodyUsed: false, _initBody: _initBody(), blob: blob(), … }

I can confirm that the server at https://api.datacite.org responds with 404 when I try to access the url https://api.datacite.org/dois/validate with a browser. If I try to access https://api.datacite.org/dois instead I do get an application/json response back that seems like it makes sense.

**Comment by yohell** [comment]
If I paste the actual application/ld+json string from the landing page in question instead, the field turns green, but still no luck when clicking Create, because "The adapter rejected the commit because it was invalid" according to console log.

> isAdapterError: true, stack: REDACTED, description: undefined, fileName: "https://doi.datacite.org/assets/vendor-0d0a3ca0092234dbe273bfb6169764b3.js", lineNumber: 6069, message: "The adapter rejected the commit because it was invalid", name: "Error", number: undefined, code: undefined, errors: (1) […]

**Comment by yohell** [comment]
Worked around my immediate problem by submitting hand written datacite xml. Would appreciate resolution though, as I would rather not have this as my main strategy for keeping dois up to date.

**Comment by mfenner** [comment]
We deployed a major fix this morning that should resolve the issue.

**Comment by yohell** [comment]
"Fabrica is currently unavailable due to a DataCite API problem. We apologize for the inconvenience and are working hard to restore the service. Please check back later or contact DataCite Support if you have a question."?

**Comment by mfenner** [comment]
This is a message you see with a temporary hickup. Please try again, Fabrica is working fine and you should be able to create or update DOIs.

**Comment by yohell** [comment]
Nope! I cannot see any buttons or similar to create DOIs, nor the usual button to Update a DOI. Logging out and logging in again does not fix this, and neither does force refresh to bypass cache. Also the url I usually use gives me a 404 (https://doi.datacite.org/clients/snd.aida/dois), idk if that is expected?

**Comment by mfenner** [comment]
Hm, I can't reproduce. The URL changed last week to https://doi.datacite.org/repositories/snd.aida/dois (see blog post https://doi.org/10.5438/apyb-7x05 and prior announcements), but that shouldn't matter if you log in via https://doi.datacite.org.

**Comment by yohell** [comment]
Ok! Though I can reproduce also with a separate browser (Chrome) different than the one I normally use (Firefox).

**Comment by mfenner** [comment]
@yohell is this now working for you?

**Comment by mfenner** [comment]
We deployed another fix, as there might have been issues with the file upload library: https://github.com/datacite/bracco/issues/263

**Comment by yohell** [comment]
Yes, now works as expected, almost??? The buttons are back, and I was able to submit, after some tomfoolery. 

When I paste in the landing page url in the metadata field and defocus, it still turns red and the form is still unsubmittable, until I put the url in "quotes". Then the field apparently validates, turns green, and the form becomes submittable. My colleague discovered that one on pure chance, and is imho quite unintuitive behavior that it would probably be good if someone could fix, or document more clearly I guess? It didn't use to behave like that did it?

**Comment by richardhallett** [comment]
Closing this issue as the original issue was in relation to other general problems with relation to file upload, which at the time was conflated with a separate issue specific to requesting using a URL in the file upload.

To note, you can use quotation marks around the URL, but that will work because it will not then try to parse the URL so you end up with blank metadata. The original schema.org metadata on the landing page.
